name: VergeStore Docs

on:
  push:
    branches:
      - main  # Set a branch name to trigger deployment
  workflow_dispatch:

env:
  SCHEME: "VergeStore"

jobs:
  deploy:
    runs-on: macos-12
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "13.3"
      - uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod
      - name: Build
        run: xcodebuild docbuild -scheme ${{ env.SCHEME }} -derivedDataPath .build -destination 'generic/platform=iOS'
      - name: Generate
        run: |
          $(xcrun --find docc) process-archive \
            transform-for-static-hosting ".build/Build/Products/Debug-iphoneos/Verge.doccarchive" \
            --output-path public \
            --hosting-base-path Verge
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
