name: VergeStore Docs

on:
  push:
    branches:
      - main # Set a branch name to trigger deployment
  workflow_dispatch:

env:
  SCHEME: "VergeStore"

jobs:
  deploy:
    runs-on: macos-12
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: maxim-lobanov/setup-xcode@v1.1
        with:
          xcode-version: "14.0"
      - uses: actions/checkout@v2
        with:
          submodules: true # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0 # Fetch all history for .GitInfo and .Lastmod
      - name: Build
        run: swift package --allow-writing-to-directory public 
          generate-documentation
          --target Verge
          --disable-indexing 
          --transform-for-static-hosting 
          --hosting-base-path swift-Verge 
          --output-path public      
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        if: ${{ github.ref == 'refs/heads/main' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
